### ISSUE TITLE
Missing license disallows free usage

### ISSUE THREAD

**Issue by l-zeuch** [Madhav-byte-debug/Yagpdb-Disboard-Reminder#1]
Hello there!
Looks like your repository is missing a license, which puts it under **exclusive copyright** and therefore disallowing free usage - which kind of defeats the purpose of this repository, if I understand the intentions correctly, as you want to allow users to use your code on their server. Correct me if I am wrong on that.

I propose the MIT license, as it is the most permissive for users, however you should decide that on your own - for advice, you can read through [this](https://choosealicense.com/) page.

Kind regards

**Comment by Madhav-byte-debug** [comment]
Thanks a ton. You have been really helpful. I'll just fork this repo to Yag's. I have added the license.

**Comment by l-zeuch** [comment]
Not a problem.
